- type: entity
  id: LockerMercenaryFilled
  suffix: Filled
  parent: LockerMercenary
  components:
  - type: StorageFill
    contents:
      - id: PinpointerUniversal
      - id: HandHeldMassScanner
      - id: WeaponGrapplingGun
      - id: BoxZiptie

- type: entity
  id: LockerNfsdSilverDetectiveFilled
  suffix: Detective, Filled
  parent: LockerNfsdSilver
  components:
  - type: StorageFill
    contents:
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: BoxEvidenceMarkers
      - id: HandLabeler
  - type: AccessReader
    access: [["Detective"]]

- type: entity
  id: NFLockerSecurityFilled
  parent: LockerSecurityFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic

- type: entity
  id: NFClosetBombFilled
  parent: ClosetBombFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool

- type: entity
  parent: GunSafe
  id: GunSafeTurrets
  name: turret safe
  suffix: NFSD, Filled
  components:
  - type: StorageFill
    contents:
    - id: WeaponCaseHeavyCdet
      amount: 2
    - id: WeaponCaseHeavySlat
      amount: 1
    - id: WeaponCaseHeavyAsmgt
      amount: 1
  - type: AccessReader
    access: [["Security"]]

- type: entity
  parent: GunSafe
  id: GunSafeTurretsCdet
  name: turret safe
  suffix: CDET, Filled
  components:
  - type: StorageFill
    contents:
    - id: WeaponCaseHeavyCdet
      amount: 1
  - type: AccessReader
    access: [["Security"]]