- type: entity
  id: LockerMercenaryFilled
  suffix: Filled
  parent: LockerMercenary
  components:
  - type: StorageFill
    contents:
      - id: PinpointerUniversal
      - id: HandHeldMassScanner
      - id: WeaponGrapplingGun
      - id: BoxZiptie
