- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
#      - id: ClothingEyesHudSecurity
#      - id: WeaponDisabler
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
#      - id: ClothingHeadHatBeretBrigmedic
#      - id: ClothingOuterCoatAMG
#      - id: ClothingUniformJumpsuitBrigmedic
#      - id: ClothingUniformJumpskirtBrigmedic
#      - id: ClothingUniformJumpskirtOfLife
#        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
#        prob: 0.6
      - id: MedkitAdvancedFilled
#        prob: 0.4
#      - id: MedkitOxygenFilled
#        prob: 0.3
#      - id: MedkitBruteFilled
#        prob: 0.3
#      - id: MedkitToxinFilled
#        prob: 0.3
#      - id: MedkitBurnFilled
#        prob: 0.7
#      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
#        prob: 0.15
#      - id: NitrogenTankFilled
#      - id: OxygenTankFilled
      - id: AirTankFilled
      - id: ClothingMaskBreathMedicalSecurity
      - id: JetpackSecurityFilled
      - id: HandheldGPSBasic
      - id: ClothingShoesBootsMagCombatFilled
      - id: HypoBrigmedic # Frontier

- type: entity
  id: LockerBrigmedicFilled
  suffix: Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
#      - id: ClothingEyesHudSecurity
#      - id: WeaponDisabler
      - id: BoxSterileMask
#      - id: ClothingHeadHatBeretBrigmedic
#      - id: ClothingOuterCoatAMG
#      - id: ClothingUniformJumpsuitBrigmedic
#      - id: ClothingUniformJumpskirtBrigmedic
#      - id: ClothingUniformJumpskirtOfLife
#        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
#        prob: 0.6
      - id: MedkitAdvancedFilled
#        prob: 0.4
#      - id: MedkitOxygenFilled
#        prob: 0.3
#      - id: MedkitBruteFilled
#        prob: 0.3
#      - id: MedkitToxinFilled
#        prob: 0.3
#      - id: MedkitBurnFilled
#        prob: 0.7
#      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
#        prob: 0.15
      - id: HypoBrigmedic # Frontier

- type: entity
  id: LockerMercenaryFilled
  suffix: Filled
  parent: LockerMercenary
  components:
  - type: StorageFill
    contents:
      - id: PinpointerUniversal
      - id: HandHeldMassScanner
      - id: WeaponGrapplingGun
      - id: BoxZiptie
