- type: entity
  id: LockerJanitorFilled
  suffix: Filled
  parent: LockerJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingBeltJanitorFilled
      - id: MopItem
      - id: BoxMousetrap
      - id: BoxTrashbag
      - id: BoxLightMixed
      - id: Plunger

- type: entity
  id: LockerClownFilled
  suffix: Filled
  parent: LockerClown
  components:
  - type: StorageFill
    contents:
      - id: ClownRecorder
      - id: BikeHorn
      - id: CrayonRainbow
      - id: RubberStampClown
      - id: SoapDeluxe
      - id: Plunger # Yes