- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 54000 # 15 hrs
#      inverted: true # stop playing intern if you're good at med!
    - !type:OverallPlaytimeRequirement # Frontier
      time: 10800 # Frontier
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  - External # Frontier
  setPreference: false # Frontier

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff
