- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackParamedicFilled
    shoes: ClothingShoesColorBlue
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  innerClothingSkirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelParamedicFilled
  duffelbag: ClothingBackpackDuffelParamedicFilled
  messenger: ClothingBackpackMessengerMedicalFilled # Frontier
