- type: job
  id: PirateFirstMate
  name: job-name-pirate-first-mate
  description: job-description-pirate-first-mate
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:WhitelistRequirement
    - !type:OverallPlaytimeRequirement
      time: 129600 # Frontier - 36 hours
  startingGear: PirateFirstMateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconMercenary" 
  supervisors: job-supervisors-hire
  setPreference: true
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]

- type: startingGear
  id: PirateFirstMateNFGear
  equipment:
    head: ClothingHeadHatPirateTricord
    ears: ClothingHeadsetAltFreelancer
    shoes: ClothingShoesBootsLaceup
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
