- type: job
  id: PirateFirstMate
  name: job-name-pirate-first-mate
  description: job-description-pirate-first-mate
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:WhitelistRequirement
    - !type:OverallPlaytimeRequirement
      time: 129600 # Frontier - 36 hours
  startingGear: NFPirateFirstMateGear
  canBeAntag: true
  alwaysUseSpawner: true
  icon: "JobIconMercenary" 
  supervisors: job-supervisors-hire
  setPreference: true
  accessGroups:
  - GeneralAccess

- type: startingGear
  id: NFPirateFirstMateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    ears: ClothingHeadsetAltFreelancer
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
  messenger: ClothingBackpackMessengerMercenaryFilled
