- type: job
  id: PirateCaptain
  name: job-name-pirate-captain
  description: job-description-pirate-captain
  playTimeTracker: JobPirateCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 172800 # 48 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 10800 # 3 hours
  whitelisted: true
  startingGear: PirateCaptainNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateCaptain"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateCaptainNFGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkRadioPirateCaptain
    pocket2: EnergyCutlass
  storage:
    back:
    - AppraisalTool
