- type: job
  id: PirateCaptain
  name: job-name-pirate-captain
  description: job-description-pirate-captain
  playTimeTracker: JobPirateCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 172800 # Frontier - 48 hours
  whitelisted: true
  startingGear: PirateCaptainNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateCaptain"
  supervisors: job-supervisors-hire
  setPreference: true
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]

- type: startingGear
  id: PirateCaptainNFGear
  equipment:
    head: ClothingHeadHatPirate
    ears: ClothingHeadsetAltFreelancer
    shoes: ClothingShoesBootsLaceup
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkRadioPirateCaptain
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  storage:
    back:
    - AppraisalTool
