- type: job
  id: Pirate
  name: job-name-pirate
  description: job-description-pirate
  playTimeTracker: JobPirate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # Frontier - 24 hours
  startingGear: PirateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirate"
  supervisors: job-supervisors-pirate
  weight: 20
  displayWeight: 20
  setPreference: true
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateNFGear
  equipment:
    head: ClothingHeadBandBlack
    ears: ClothingHeadsetAltFreelancer
    shoes: ClothingShoesBootsLaceup
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
    pocket2: AppraisalTool
