- type: ghostRole
  id: BabyDragon
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: DragonEgg # Unsure if this should be MobDragonPet (the actual dragon) - no ghost role component
  whitelisted: true

# Pets
- type: ghostRole
  id: EmotionalSupportPet
  name: ghost-role-information-emotional-support-name
  description: ghost-role-information-emotional-support-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatGhost # TODO: replace this with a random emotional support pet entity
  whitelisted: true

# Others
- type: ghostRole
  id: CatCappy
  name: ghost-role-information-cappy-name
  description: ghost-role-information-cappy-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatCappy
  whitelisted: true

- type: ghostRole
  id: CatClarpy
  name: ghost-role-information-clarpy-name
  description: ghost-role-information-clarpy-description
  rules:  ghost-role-information-emotional-support-rules
  entityPrototype: MobCatClarpy
  whitelisted: true

- type: ghostRole
  id: CatClippy
  name: ghost-role-information-clippy-name
  description: ghost-role-information-clippy-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatClippy
  whitelisted: true

- type: ghostRole
  id: CatMistake
  name: ghost-role-information-mistake-name
  description: ghost-role-information-mistake-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatMistake
  whitelisted: true

- type: ghostRole
  id: MonkeyPunpun
  name: ghost-role-information-punpun-name
  description: ghost-role-information-punpun-description
  rules: ghost-role-information-nonantagonist-rules
  entityPrototype: MobMonkeyPunpun
  whitelisted: true

- type: ghostRole
  id: SentientArtifact
  name: ghost-role-information-artifact-name
  description: ghost-role-information-artifact-description
  rules: ghost-role-information-freeagent-rules
  entityPrototype: VariedXenoArtifactItem # Don't spawn this.  FIXME: entity has no ghost role component.
  whitelisted: true

- type: ghostRole
  id: KoboldYipyip
  name: ghost-role-information-yipyip-name
  description: ghost-role-information-yipyip-description
  rules: ghost-role-information-nonantagonist-rules
  entityPrototype: MobKoboldYipyip
  whitelisted: true

# Other others
- type: ghostRole
  id: GhostMemeGoblinbane
  name: ghost-role-information-goblinbane-name
  description: ghost-role-information-goblinbane-description
  rules: ghost-role-information-goblinbane-rules
  entityPrototype: BaseMobMemeGoblinbane
  whitelisted: true
