- type: playTimeTracker
  id: JobERTMailCarrier

- type: playTimeTracker
  id: JobMercenary

- type: playTimeTracker
  id: JobPilot

- type: playTimeTracker
  id: JobPublicAffairsLiaison

- type: playTimeTracker
  id: JobSecurityGuard

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobStc

- type: playTimeTracker
  id: JobPirateCaptain
  
- type: playTimeTracker
  id: JobPirateFirstMate
  
- type: playTimeTracker
  id: JobPirate