- type: playTimeTracker
  id: JobContractorInterview

- type: playTimeTracker
  id: JobDirectorOfCare

- type: playTimeTracker
  id: JobERTMailCarrier

- type: playTimeTracker
  id: JobMailCarrier

- type: playTimeTracker
  id: JobMercenary

- type: playTimeTracker
  id: JobMercenaryInterview

- type: playTimeTracker
  id: JobPilot

- type: playTimeTracker
  id: JobPilotInterview

- type: playTimeTracker
  id: JobPirateCaptain

- type: playTimeTracker
  id: JobPirateFirstMate

- type: playTimeTracker
  id: JobPirate

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobPrisonGuard

- type: playTimeTracker
  id: JobPublicAffairsLiaison

- type: playTimeTracker
  id: JobSecurityGuard

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobStc

- type: playTimeTracker
  id: JobValet

- type: playTimeTracker
  id: ShuttleAiCivilian

- type: playTimeTracker
  id: ShuttleAiNFSD

- type: playTimeTracker
  id: ShuttleAiCentCom

- type: playTimeTracker
  id: ShuttleAiFreelance

- type: playTimeTracker
  id: ShuttleAiSyndicate

- type: playTimeTracker
  id: ForeignEnsign

- type: playTimeTracker
  id: ForeignLieutenant
