- type: playTimeTracker
  id: JobSecurityCadetOld

- type: playTimeTracker
  id: JobSecurityOfficerOld

- type: playTimeTracker
  id: JobHeadOfSecurityOld

- type: playTimeTracker
  id: JobWardenOld

- type: playTimeTracker
  id: JobDetectiveOld

- type: playTimeTracker
  id: JobHeadOfPersonnelOld

- type: playTimeTracker
  id: JobPassengerOld

- type: playTimeTracker
  id: JobJanitorOld