- type: sectorService
  id: PirateBounties
  components:
  - type: SectorPirateBountyDatabase

- type: sectorService
  id: MailMetrics
  components:
  - type: SectorLogisticStats

- type: sectorService
  id: ShuttleRecords
  components:
  - type: SectorShuttleRecords

- type: sectorService
  id: BankAccounts
  components:
  - type: SectorBank
    accounts:
      Frontier:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 1 # TODO: move to ~65K per hour (~18/s), about enough for minimum wage for Frontier employees
      Nfsd:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 20 # 72K per hour, about enough for minimum wage for the default NFSD size
      Medical:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 6 # 21.6K per hour, a bit over for the DOC MOM's wage.

 # A global source of character records (DNA, fingerprints, criminal records, etc.)
- type: sectorService
  id: SectorRecords
  components:
  - type: StationRecords

- type: sectorService
  id: Alerts
  components:
  - type: AlertLevel
    alertLevelPrototype: stationAlerts
