- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  # requirements:
    # - !type:RoleTimeRequirement
      # role: JobHeadOfPersonnel
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobHeadOfSecurity
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobChiefMedicalOfficer
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobChiefEngineer
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobResearchDirector
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobQuartermaster
      # time: 21600 #6 hrs
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Captain # Just making sure in the case of any error that this role cannot be used for any bad doing.
  - Maintenance # Frontier
  - External # Frontier
  # accessGroups:
  # - AllAccess
  # special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
    # components:
      # - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    # ears: ClothingHeadsetAltCommand
    ears: ClothingHeadsetGrey
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
