- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedicFilled
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretSecurity
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponPistolMk58Nonlethal # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled
