- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1400
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External


- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedicFilled
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
    neck: ClothingNeckBodycam
  innerclothingskirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled
