- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurityOld # Frontier JobHeadOfSecurity<JobHeadOfSecurityOld
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # 30 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  ## Frontier: commented out stuff below
  # access:
  # - HeadOfSecurity
  # - Command
  # - Brig
  # - Security
  # - Armory
  # - Maintenance
  # - Service
  # - External
  # - Detective
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
  #   components:
  #     - type: CommandStaff
  ## Frontier: commented out stuff above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol