- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWardenOld
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
<<<<<<< HEAD
      time: 36000 #10 hrs
  # weight: 5 # Frontier
=======
      time: 10h
  weight: 5
>>>>>>> e917c8e067e70fa369bf8f1f393a465dc51caee8
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  ## Frontier: commented out stuff below
  # access:
  # - Security
  # - Brig
  # - Armory
  # - Maintenance
  # - Service
  # - External
  # - Detective
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    pocket1: NFWeaponPistolMk58 # Frontier: use NF variant
  storage:
    back:
    - Flash
    - NFMagazinePistol35 # Frontier: MagazinePistol<NFMagazinePistol35

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
