# Leader
- type: startingGear
  id: BloodCultistPriestGear
  equipment:
    head: ClothingHeadHelmetCult
    shoes: ClothingShoesCult
    gloves: ClothingHandsGlovesCombat
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    belt: ClothingBeltCultWebbing
    back: ClothingBackpackBloodCultLootA
  inhand:
    - WizardStaffMeleeBlood

# Acolyte
- type: startingGear
  id: BloodCultistAcolyteGear
  equipment:
    head: ClothingHeadHelmetCult
    shoes: ClothingShoesCult
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCult
    back: ClothingBackpackBloodCultLootB
    belt: ClothingBeltCultWebbing
  inhand:
    - EldritchBlade

# Cultist (Melee)
- type: startingGear
  id: BloodCultistZealotMeleeGear
  equipment:
    head: ClothingHeadHatHoodBloodCulthoodUnremoveable
    shoes: ClothingShoesCult
    gloves: ClothingHandsGlovesCombat
    mask: ClothingMaskJackal
    outerClothing: ClothingOuterCoatBloodCultRobes
    belt: ClothingBeltCultWebbing
    back: ClothingBackpackBloodCultLootD
  inhand:
    - EldritchBlade

# Cultist (Ranged)
- type: startingGear
  id: BloodCultistZealotRangedGear
  equipment:
    head: ClothingHeadHatHoodBloodCulthoodUnremoveable
    shoes: ClothingShoesCult
    mask: ClothingMaskRaven
    gloves: ClothingHandsGlovesColorBlackCrossbow
    outerClothing: ClothingOuterCoatBloodCultRobes
    back: ClothingBackpackBloodCultZealotLootA
    belt: ClothingBeltQuiverCrossbowFilledBolt
  inhand:
    - EldritchBlade

# Cultist (Caster)
- type: startingGear
  id: BloodCultistCasterGear
  equipment:
    head: ClothingHeadHatHoodBloodCulthoodUnremoveable
    shoes: ClothingShoesCult
    mask: ClothingMaskRaven
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatBloodCultRobes
    back: ClothingBackpackBloodCultLootC
    belt: ClothingBeltCultWebbing
  inhand:
    - WizardStaffMeleeBlood

# Janitor (Caster)
- type: startingGear
  id: BloodCultistJanitorGear
  equipment:
    head: ClothingHeadHelmetCultJanitor
    shoes: ClothingShoesCult
    mask: ClothingMaskCultJanitor
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatCultJanitor
    belt: ClothingBeltCultForceField
    back: ClothingBackpackBloodCultLootA
  inhand:
    - EldritchBlade
