# Tier 1
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT1
  equipment:
    gloves: ClothingHandsGlovesWeaponWieldedPickaxe
    back: ClothingBackpackExplorerMeleeT1
    belt: OreBag
    shoes: ClothingShoesBootsSalvage
    suitstorage: AirTankFilled
    neck: ClothingNeckIFFCyan

- type: startingGear
  id: MobHumanoidExplorerGearRangedT1
  equipment:
    gloves: ClothingHandsGlovesWeaponPkaFlashlight
    back: ClothingBackpackExplorerRangedT1
    belt: ConstructionBag
    shoes: ClothingShoesBootsSalvage
    suitstorage: AirTankFilled
    neck: ClothingNeckIFFCyan

# Tier 2
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT2
  equipment:
    gloves: ClothingHandsGlovesWeaponWieldedGlaive
    outerClothing: ClothingOuterHardsuitSpatio
    back: ClothingBackpackExplorerMeleeT2
    belt: OreBag
    shoes: ClothingShoesBootsSalvage
    neck: ClothingNeckIFFCyan

- type: startingGear
  id: MobHumanoidExplorerGearRangedT2
  equipment:
    gloves: ClothingHandsGlovesWeaponSawnOffPkaDagger
    outerClothing: ClothingOuterHardsuitSpatio
    back: ClothingBackpackExplorerRangedT2
    belt: ConstructionBag
    shoes: ClothingShoesBootsSalvage
    neck: ClothingNeckIFFCyan

# Tier 3
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT3
  equipment:
    gloves: ClothingHandsGlovesWeaponDrill
    outerClothing: ClothingOuterHardsuitSalvage
    back: ClothingBackpackExplorerMeleeT3
    belt: OreBag
    shoes: ClothingShoesBootsSalvage
    neck: ClothingNeckIFFCyan

- type: startingGear
  id: MobHumanoidExplorerGearRangedT3
  equipment:
    gloves: ClothingHandsGlovesWeaponWieldedPka
    outerClothing: ClothingOuterHardsuitLuxury
    back: ClothingBackpackExplorerRangedT3
    belt: ConstructionBag
    shoes: ClothingShoesBootsSalvage
    neck: ClothingNeckIFFCyan

- type: startingGear
  id: MobHumanoidExplorerGearMechT3
  equipment:
    pocket1: RipleyCentralElectronics
    pocket2: RipleyPeripheralsElectronics

# Tier 4
- type: startingGear
  id: MobHumanoidExplorerGearBoss
  equipment:
    gloves: ClothingHandsGlovesWeaponEnergyPickaxe
    outerClothing: ClothingOuterHardsuitMaximPrototype
    back: ClothingBackpackExplorerBoss
    belt: ConstructionBag
    shoes: ClothingShoesBootsSalvage
    neck: ClothingNeckIFFCyan
