# Tier 1
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT1
  equipment:
    pocket1: ClothingBackpackExplorerMeleeT1
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT1

- type: startingGear
  id: MobHumanoidExplorerGearRangedT1
  equipment:
    pocket1: ClothingBackpackExplorerRangedT1
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT1

# Tier 2
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT2
  equipment:
    pocket1: ClothingBackpackExplorerMeleeT2
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT2

- type: startingGear
  id: MobHumanoidExplorerGearRangedT2
  equipment:
    pocket1: ClothingBackpackExplorerRangedT2
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT2

# Tier 3
- type: startingGear
  id: MobHumanoidExplorerGearMeleeT3
  equipment:
    pocket1: ClothingBackpackExplorerMeleeT3
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT3

- type: startingGear
  id: MobHumanoidExplorerGearRangedT3
  equipment:
    pocket1: ClothingBackpackExplorerRangedT3
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerT3

# Tier 4
- type: startingGear
  id: MobHumanoidExplorerGearBoss
  equipment:
    pocket1: ClothingBackpackExplorerBoss
    shoes: ClothingShoesBootsSalvage
    suitstorage: NFTankO2N2EqualFilled
    neck: ClothingNeckIFFCyan
    wallet: ClothingWalletExplorerBoss
