# Tier 1
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT1
  equipment:
    gloves: ClothingHandsGlovesColorMercHatchet
    back: ClothingBeltMercenaryLootMeleeT1
    shoes: ClothingShoesBootsMercenary
    wallet: ClothingWalletMercenaryT1

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT1
  equipment:
    gloves: ClothingHandsGlovesColorMercPistol
    back: ClothingDuffelMercenaryLootRangedT1
    belt: ClothingBeltMercenaryLootRangedT1
    shoes: ClothingShoesBootsMercenary
    wallet: ClothingWalletMercenaryT1

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT1
  equipment:
    gloves: ClothingHandsGlovesColorMercNovalite
    back: ClothingDuffelMercenaryLootRangedAltT1
    belt: ClothingBeltMercenaryLootRangedAltT1
    shoes: ClothingShoesBootsMercenary
    wallet: ClothingWalletMercenaryT1

# Tier 2
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT2
  equipment:
    gloves: ClothingHandsGlovesColorMercMachete
    back: ClothingDuffelMercenaryLootMeleeT2
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryT2

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT2
  equipment:
    gloves: ClothingHandsGlovesColorMercShotgun
    back: ClothingDuffelMercenaryLootRangedT2
    belt: ClothingBeltMercenaryLootRangedT2
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryT1

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT2
  equipment:
    gloves: ClothingHandsGlovesColorMercRevolvers
    back: ClothingDuffelMercenaryLootRangedAltT2
    belt: ClothingBeltMercenaryLootRangedAltT2
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryT2

# Tier 3
- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3
  equipment:
    gloves: ClothingHandsGlovesColorMercLaserNSaw
    back: ClothingDuffelMercenaryLootRangedT3
    belt: ClothingBeltMercenaryLootRangedT3
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryT3

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT3
  equipment:
    gloves: ClothingHandsGlovesColorMercGestio
    back: ClothingDuffelMercenaryLootRangedAltT3
    belt: ClothingBeltMercenaryLootRangedAltT3
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryT3

# Tier 4
- type: startingGear
  id: MobHumanoidMercenaryGearBoss
  equipment:
    gloves: ClothingHandsGlovesColorMercRepeater
    back: ClothingDuffelMercenaryLootBoss
    shoes: ClothingShoesBootsCombat
    wallet: ClothingWalletMercenaryBoss
