# Tier 1
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT1
  equipment:
    gloves: ClothingHandsGlovesColorMercHatchet
    pocket1: SpaceCash500
    pocket2: HydroponicsToolHatchet
    shoes: ClothingShoesBootsMercenary

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT1
  equipment:
    gloves: ClothingHandsGlovesColorMercPistol
    back: ClothingBackpackDuffelMecranaryTier1Pistol
    belt: ClothingBeltWebbingMecranaryTier1Pistol
    shoes: ClothingShoesBootsMercenary

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT1
  equipment:
    gloves: ClothingHandsGlovesColorMercNovalite
    back: ClothingBackpackDuffelMecranaryTier1Novalite
    belt: ClothingBeltWebbingMecranaryTier1Novalite
    shoes: ClothingShoesBootsMercenary

# Tier 2
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT2
  equipment:
    gloves: ClothingHandsGlovesColorMercMachete
    pocket1: Machete
    pocket2: SpaceCash1000
    shoes: ClothingShoesBootsCombat

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT2
  equipment:
    gloves: ClothingHandsGlovesColorMercRevolvers
    back: ClothingBackpackDuffelMecranaryTier2Revolver
    belt: ClothingBeltWebbingMecranaryTier2Revolver
    shoes: ClothingShoesBootsCombat

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT2
  equipment:
    gloves: ClothingHandsGlovesColorMercShotgun
    back: ClothingBackpackDuffelMecranaryTier2Shotgun
    belt: ClothingBeltWebbingMecranaryTier2Shotgun
    shoes: ClothingShoesBootsCombat

# Tier 3
- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3
  equipment:
    gloves: ClothingHandsGlovesColorMercLaserNSaw
    back: ClothingBackpackDuffelMecranaryTier3Medic
    belt: ClothingBeltMecranaryTier3Medic
    shoes: ClothingShoesBootsCombat

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3Alt
  equipment:
    gloves: ClothingHandsGlovesColorMercGestio
    back: ClothingBackpackDuffelMecranaryTier3Assault
    belt: ClothingBeltMecranaryTier3Assault
    shoes: ClothingShoesBootsCombat

# Tier 4
- type: startingGear
  id: MobHumanoidMercenaryGearTier4Captain
  equipment:
    gloves: ClothingHandsGlovesColorMercRepeater
    back: ClothingBackpackDuffelMecranaryTier4Captain
    shoes: ClothingShoesBootsCombat
