# region Tier 1
- type: startingGear
  id: PunkGangerGearMeleeT1
  equipment:
    neck: PunkHandsGlovesBaseballBat
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkMeleeT1
    wallet: ClothingWalletPunkT1

- type: startingGear
  id: PunkGangerGearPistol
  equipment:
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    gloves: ClothingHandsGlovesColorBlackPistol
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkRangedT1
    wallet: ClothingWalletPunkT1

# region Tier 2
- type: startingGear
  id: PunkGangerGearMeleeT2
  equipment:
    neck: PunkHandsGlovesFireaxe
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    pocket2: ClothingBackpackPunkMeleeT1 # TODO: MeleeT2
    wallet: ClothingWalletPunkT2

- type: startingGear
  id: PunkGangerGearShotgun
  equipment:
    neck: PunkHandsGlovesShotgun
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkRangedT2
    wallet: ClothingWalletPunkT2

# region Tier 3
- type: startingGear
  id: PunkGangerGearMeleeT3
  equipment:
    neck: PunkHandsGlovesSledgehammer
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    pocket2: ClothingBackpackPunkMeleeT1 # TODO: MeleeT3
    wallet: ClothingWalletPunkT3

- type: startingGear
  id: PunkGangerGearSmg
  equipment:
    neck: PunkHandsGlovesSmg
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    pocket2: ClothingBackpackPunkRangedT3
    wallet: ClothingWalletPunkT3

# region Tier 4
- type: startingGear
  id: PunkGangerGearLaser
  equipment:
    neck: PunkHandsGlovesLaserGun
    eyes: ClothingEyesPunkInfoShades
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    back: PortableRecharger
    pocket2: ClothingBackpackPunkLootBoss
    wallet: ClothingWalletPunkBoss
