# Tier 0
- type: startingGear
  id: MobRogueSiliconLootT0
  equipment:
    back: ClothingBackpackRogueSiliconT0

# Tier 1
- type: startingGear
  id: MobRogueSiliconLootT1
  equipment:
    back: ClothingBackpackRogueSiliconT1

# Tier 2
- type: startingGear
  id: MobRogueSiliconLootT2
  equipment:
    back: ClothingBackpackRogueSiliconT2

# Tier 3
- type: startingGear
  id: MobRogueSiliconLootT3
  equipment:
    back: ClothingBackpackRogueSiliconT3

# Tier 4
- type: startingGear
  id: MobRogueSiliconLootT4
  equipment:
    back: ClothingBackpackRogueSiliconT4
