# region Tier 1
# Syndicate Deckhand
- type: startingGear
  id: SyndicateNavalGearT1Deckhand
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndieNF
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlackPistol
    belt: ClothingBeltSyndicateLootRangedT1Deckhand
    back: ClothingBackpackSyndicateT1Deckhand
    wallet: ClothingWalletSyndicateT1
  inhand:
    - PowerDrill

# Syndicate Saboteur
- type: startingGear
  id: SyndicateNavalGearT1Saboteur
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPistol
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterArmorBasicSlim
    belt: ClothingBeltSyndicateLootRangedT1Saboteur
    back: ClothingBackpackSyndicateT1Saboteur
    wallet: ClothingWalletSyndicateT1
  inhand:
    - CombatKnife

# Syndicate Experimentation Victim
- type: startingGear
  id: SyndicateVictimInsaneGear
  equipment:
    outerClothing: ClothingOuterHospitalGown
    mask: ClothingMaskMuzzle
    neck: ClothingMultipleHeadphones
  inhand:
    - ReinforcedShiv

# region Tier 2
# Captain
- type: startingGear
  id: SyndicateNavalGearT2Captain
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormalNF
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    outerClothing: ClothingOuterCoatSyndieCapArmored
    belt: ClothingBeltSyndicateLootRangedT2Captain
    back: ClothingBackpackSyndicateT2Captain
    wallet: ClothingWalletSyndicateT2
  inhand:
    - PlasteelArmingSword

# Engineer
- type: startingGear
  id: SyndicateNavalGearT2Engineer
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndieNF
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackShotgun
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltSyndicateLootRangedT2Engineer
    back: ClothingBackpackSyndicateT2Engineer
    wallet: ClothingWalletSyndicateT2
  inhand:
    - ToolboxEmergency

# Medic
- type: startingGear
  id: SyndicateNavalGearT2Medic
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndieNF
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatAMG
    belt: ClothingBeltSyndicateLootRangedT2Medic
    back: ClothingBackpackSyndicateT2Medic
    wallet: ClothingWalletSyndicateT2
  inhand:
    - SawAdvanced

# Syndicate Second Officer
- type: startingGear
  id: SyndicateNavalGearT2SecondOfficer
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndieNF
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackLaserPistol
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterArmorBasic
    back: ClothingBackpackSyndicateT2SecondOfficer
    wallet: ClothingWalletSyndicateT2
  inhand:
    - Cutlass

# region Tier 3
# Syndicate Security Operative
- type: startingGear
  id: SyndicateNavalGearT3Operator
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackSMG
    outerClothing: ClothingOuterArmorBulletproof
    back: ClothingBackpackSyndicateT3Operative
    belt: ClothingBeltSyndicateLootRangedT3Operative
    wallet: ClothingWalletSyndicateT3
  inhand:
    - KukriKnife

# Syndicate Grenadier
- type: startingGear
  id: SyndicateNavalGearT3Grenadier
  equipment:
    head: ClothingHeadHelmetBombSuitSyndie
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateRed
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlackChinaLake
    outerClothing: ClothingOuterSuitBombSyndie
    back: ClothingBackpackSyndicateT3Grenadier
    belt: ClothingBeltSyndicateLootRangedT3Grenadier
    wallet: ClothingWalletSyndicateT3

# Syndicate Mime
- type: startingGear
  id: SyndicateNavalGearT3Mime
  equipment:
    head: ClothingHeadHatBeret
    mask: ClothingMaskMime
    neck: ClothingNeckScarfStripedSyndieRed
    jumpsuit: ClothingUniformJumpsuitMime
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorBulletproof
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackSyndicateT2Captain
    wallet: ClothingWalletSyndicateT3
  inhand:
    - Chainsaw

# Syndicate Chemwarrior
- type: startingGear
  id: SyndicateNavalGearT3Chemwarrior
  equipment:
    head: ClothingHeadHatHoodBioArmoredSyndicate
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateRed
    gloves: ClothingHandsGlovesColorBlackSprayNozzle
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterBioArmoredSyndicate
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackSyndicateT3Chemwarrior
    wallet: ClothingWalletSyndicateT3
  inhand:
    - SpearPlasma

# Syndicate Chemwarrior (Alt)
- type: startingGear
  id: SyndicateNavalGearT3ChemwarriorAlt
  equipment:
    head: ClothingHeadHatHoodWinterSyndieUnremoveable
    neck: ClothingNeckScarfStripedSyndieRed
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateRed
    gloves: ClothingHandsGlovesColorBlackSprayNozzle
    shoes: ClothingShoesBootsWinterSyndicate
    outerClothing: ClothingOuterWinterSyndie
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackSyndicateT3ChemwarriorAlt
    wallet: ClothingWalletSyndicateT3
  inhand:
    - SpearUranium

# region Tier 4 (Boss)
# Syndicate Commander
- type: startingGear
  id: SyndicateNavalGearT4Commander
  equipment:
    neck: BedsheetSyndie
    jumpsuit: ClothingUniformJumpsuitSyndieFormalNF
    outerClothing: ClothingOuterHardsuitSyndieEliteUnremoveable
    head: ClothingHeadHelmetHardsuitSyndieEliteUnremoveable
    gloves: ClothingHandsGlovesColorBlackAK
    shoes: ClothingShoesBootsMagSyndie
    back: ClothingBackpackSyndicateT4Commander
    belt: ClothingBeltSyndicateLootRangedT4Commander
    wallet: ClothingWalletSyndicateT4
  inhand:
    - CaptainSabre

# region Void Gear
# Syndicate Deckhand Void
- type: startingGear
  id: SyndicateNavalDeckhandVoidGear
  equipment:
    head: ClothingHeadHelmetSyndicate
    outerClothing: ClothingOuterEVASuitSyndicate
    jumpsuit: ClothingUniformJumpsuitRecruitSyndieNF
    shoes: ClothingShoesBootsMagSyndie
    gloves: ClothingHandsGlovesColorBlackPistol
    belt: ClothingBeltSyndicateLootRangedT1Deckhand
    back: ClothingBackpackSyndicateT1Deckhand
    wallet: ClothingWalletSyndicateT1
  inhand:
    - Crowbar

# Engineer Void
- type: startingGear
  id: SyndicateNavalEngineerVoidGear
  equipment:
    head: ClothingHeadHelmetSyndicate
    outerClothing: ClothingOuterEVASuitSyndicate
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndieNF
    shoes: ClothingShoesBootsMagSyndie
    gloves: ClothingHandsGlovesColorBlackShotgun
    belt: ClothingBeltSyndicateLootRangedT2Engineer
    back: ClothingBackpackSyndicateT2Engineer
    wallet: ClothingWalletSyndicateT2
  inhand:
    - ToolboxSyndicate

# Syndicate Security Operative Void
- type: startingGear
  id: SyndicateNavalOperatorVoidGear
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieUnremoveable
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsMagSyndie
    gloves: ClothingHandsGlovesColorBlackSMG
    outerClothing: ClothingOuterHardsuitSyndieBloodRedUnremoveable
    back: ClothingBackpackSyndicateT3Operative
    belt: ClothingBeltSyndicateLootRangedT3Operative
    wallet: ClothingWalletSyndicateT3
  inhand:
    - KukriKnife

# Syndicate Second Officer Void
- type: startingGear
  id: SyndicateNavalSecondOfficerVoidGear
  equipment:
    head: ClothingHeadHatHoodBioArmoredSyndicate
    jumpsuit: ClothingUniformJumpsuitRecruitSyndieNF
    shoes: ClothingShoesBootsMagSyndie
    gloves: ClothingHandsGlovesColorBlackLaserPistol
    outerClothing: ClothingOuterHardsuitSyndieBloodRedUnremoveable
    back: ClothingBackpackSyndicateT2SecondOfficer
    wallet: ClothingWalletSyndicateT2
  inhand:
    - Machete

# Syndicate Captain Void
- type: startingGear
  id: SyndicateNavalCaptainVoidGear
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieEliteUnremoveable
    jumpsuit: ClothingUniformJumpsuitSyndieFormalNF
    shoes: ClothingShoesBootsMagSyndie
    gloves: ClothingHandsGlovesColorBlackPython
    neck: ClothingNeckScarfStripedSyndieRed
    outerClothing: ClothingOuterHardsuitSyndieEliteUnremoveable
    belt: ClothingBeltSyndicateLootRangedT2Captain
    back: ClothingBackpackSyndicateT2Captain
    wallet: ClothingWalletSyndicateT2
  inhand:
    - PlasteelArmingSword

# Syndicate Medic Void
- type: startingGear
  id: SyndicateNavalMedicVoidGear
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedicUnremoveable
    jumpsuit: ClothingUniformJumpsuitParamedicSyndieNF
    shoes: ClothingShoesBootsMagSyndie
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterHardsuitSyndieMedic
    belt: ClothingBeltSyndicateLootRangedT2Medic
    back: ClothingBackpackSyndicateT2Medic
    wallet: ClothingWalletSyndicateT2
  inhand:
    - SawAdvanced
