# Captain
- type: startingGear
  id: SyndicateNavalCaptainGear
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckScarfStripedSyndieRed
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatSyndieCapArmored
    pocket1: WeaponRevolverPythonAP
  inhand:
    - PlasteelArmingSword

# Engineer
- type: startingGear
  id: SyndicateNavalEngineerGear
  equipment:
    head: ClothingHeadHatHardhatRed
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    back: ClothingBackpackDuffelSyndicateAmmo
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltUtility
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
  inhand:
    - WeaponShotgunKammerer

# Medic
- type: startingGear
  id: SyndicateNavalMedicGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    back: ClothingBackpackDuffelSyndicateMedical
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMedical
    neck: ClothingNeckStethoscope
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterCoatAMG
  inhand:
    - SawAdvanced

# Syndicate Second Officer
- type: startingGear
  id: SyndicateNavalSecondOfficerGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasic
  inhand:
    - WeaponAdvancedLaser

# Syndicate Security Operative
- type: startingGear
  id: SyndicateNavalOperatorGear
  equipment:
    head: ClothingHeadHelmetSwatSyndicate
    jumpsuit: ClothingUniformJumpsuitOperative
    back: WeaponSubMachineGunAtreides
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBulletproof
  inhand:
    - KukriKnife

# Syndicate Grenadier
- type: startingGear
  id: SyndicateNavalGrenadierGear
  equipment:
    head: ClothingHeadHelmetBombSuit
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMilitaryWebbing
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterSuitBomb

# Syndicate Saboteur
- type: startingGear
  id: SyndicateNavalSaboteurGear
  equipment:
    head: ClothingHeadHatSyndie
    back: JetpackBlackFilled
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskNeckGaiter
    outerClothing: ClothingOuterArmorBasicSlim
#    pocket1: WeaponPistolViper
  inhand:
    - CombatKnife

# Syndicate Victim: Driven Insane Victim of Experimentation
- type: startingGear
  id: SyndicateVictimInsaneGear
  equipment:
    outerClothing: ClothingOuterHospitalGown
    mask: ClothingMaskMuzzle
    neck: ClothingNeckHeadphones
  inhand:
    - ReinforcedShiv

# Commander (Megafauna for dungeons)
- type: startingGear
  id: SyndicateNavalCommanderGear
  equipment:
    mask: ClothingMaskGasSyndicate
    neck: BedsheetSyndie
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterHardsuitSyndieElite
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsMagSyndie
    back: WeaponRifleAk
    pocket1: MagazineLightRifle
    pocket2: MagazineLightRifle
  inhand:
    - CaptainSabre
    
# Syndicate Deckhand
- type: startingGear
  id: SyndicateNavalDeckhandGear
  equipment:
    head: ClothingHeadHatSyndie
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterArmorBasic
    pocket1: WeaponPistolViper
  inhand:
    - CombatKnife

# Syndicate Mime
- type: startingGear
  id: SyndicateNavalMimeGear
  equipment:
    head: ClothingHeadHatBeret
    mask: ClothingMaskMime
    neck: ClothingNeckScarfStripedSyndieRed
    jumpsuit: ClothingUniformJumpsuitMime
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorBulletproof
    belt: ClothingBeltSyndieHolster
    eyes: ClothingEyesHudSyndicate
    back: ClothingBackpackMessengerSyndicate
    pocket1: Stimpack
    pocket2: Stimpack
  inhand:
    - Chainsaw
