- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
#    belt: ClothingBeltUtilityEngineering # Frontier - Moved to locker
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
