- type: job
  id: KommissarNCWL
  name: job-name-kommissar
  description: job-description-kommissar
  playTimeTracker: JobKommissarNCWL
  requirements:
    - !type:WhitelistRequirement
  weight: 55
  startingGear: KommissarGear
  alwaysUseSpawner: true
  icon: "JobIconCommissar"
  requireAdminNotify: true
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - NCWLGeneral
  - Service
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KommissarGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLKommissar
    back: ClothingBackpackSatchelLeatherFilledNCWL
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatNCWLKommissarHat
    outerClothing: ClothingOuterArmorNCWLCarapace
    id: KommissarPDA
    ears: ClothingHeadsetNCWL
    belt: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
