- type: startingGear
  id: MobEmotionalSupportGear
  equipment:
    id: PassengerIDCard

- type: startingGear
  id: MobClippyGear
  equipment:
#    ears: ClothingHeadsetService
    id: MailCarrierIDCard

- type: startingGear
  id: MobClarpyGear
  equipment:
#    ears: ClothingHeadsetService
    id: AgentIDCard

- type: startingGear
  id: MobCrispyGear
  equipment:
#    ears: ClothingHeadsetService
    id: AgentIDCard

- type: startingGear
  id: MobMistakeGear
  equipment:
    id: PassengerIDCard
