- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - External # Frontier

- type: startingGear
  id: BoxerGear
  equipment:
    jumpsuit: UniformShortsRed
    back: ClothingBackpackFilled
    id: BoxerPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesBoxingRed
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  innerClothingSkirt: UniformShortsRedWithTop
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
