- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  #storage:
    #back:
    #- Stuff
