- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External # Frontier
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackPsychologistFilled # Frontier
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  innerClothingSkirt: ClothingUniformJumpsuitPsychologist
  satchel: ClothingBackpackSatchelPsychologistFilled # Frontier
  duffelbag: ClothingBackpackDuffelPsychologistFilled # Frontier
