[game]
hostname = "ğŸŒ“ Project Eclipse - Ğ¤Ğ ĞĞĞ¢Ğ˜Ğ ! ğŸŒ—"
#desc             = "Official English Space Station 14 servers. Vanilla, roleplay ruleset."
lobbyenabled     = true
maxplayers = 150
soft_max_players = 80

[game.panic_bunker]
enabled = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
disable_with_admins = true
enable_without_admins = true
show_reason = true

[infolinks]
bug_report = "https://github.com/Apxumekm0p/Eclipse-New-Frontier/issues/new/choose"
discord    = "https://discord.gg/BH39NH4"
#forum      = "https://forum.spacestation14.io"
github     = "https://github.com/Apxumekm0p/Eclipse-New-Frontier"
#patreon    = "https://www.patreon.com/spacestation14"
#website    = "https://spacestation14.io"
#wiki       = "https://wiki.spacestation14.io"
#appeal     = "https://appeal.ss14.io"

[hub]
advertise = false
tags = ""

[server]
rules_file = "StandardRuleset"

[net]
tickrate = 60

[netres]
limit = 25.0

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2

[auth]
mode = 1