[net]
max_connections = 256
pvs_range = 20.0
pvs_priority_range = 30.0
tickrate = 60

[game]
maxplayers = 150
soft_max_players = 100
hostname = "üåí Project Eclipse - –§–†–û–ù–¢–ò–†! [18+] üåí"
desc = "üåí–ù–∞—á–Ω–∏ —Å–≤–æ–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ –Ω–∞ —Å–µ–∫—Ç–æ—Ä–µ –≠–ö–õ–ò–ü–° –ø—Ä—è–º–æ —Å–µ–π—á–∞—Å!\nüåí–£–Ω–∏–∫–∞–ª—å–Ω–∞—è —Å–∏—Å—Ç–µ–º–∞ —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∏—è —Å–≤–æ–µ–≥–æ —à–∞—Ç—Ç–ª–∞, –ø–æ—Å—Ç—Ä–æ–π —Å–≤–æ–π —à–∞—Ç—Ç–ª –º–µ—á—Ç—ã!\n\nüíé–ù–∞ —Å–µ—Ä–≤–µ—Ä–µ —Å—Ä–µ–¥–Ω–∏–π —É—Ä–æ–≤–µ–Ω—å –æ—Ç—ã–≥—Ä—ã—à–∞ –†–ü.\nüíé–°–º–µ–Ω—ã –∏–¥—É—Ç –ø–æ 72 —á–∞—Å–∞, –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –¥–ª—è –≤–æ–ø–ª–æ—â–µ–Ω–∏—è –≤–∞—à–∏—Ö —Ñ–∞–Ω—Ç–∞–∑–∏–π!\nüíé–ú–Ω–æ–∂–µ—Å—Ç–≤–æ —Å–≤–æ–∏—Ö —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Å–∏—Å—Ç–µ–º, —É–ª—É—á—à–µ–Ω–∏–π –∏ —Ä–∞–∑—Ä–∞–±–æ—Ç–æ–∫!\nüíé–ü–æ—Å—Ç—Ä–æ–π—Ç–µ —à–∞—Ç—Ç–ª —Å–≤–æ–µ–π –º–µ—á—Ç—ã, –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–∏–µ —Ç–æ–ª—å–∫–æ –≤–∞—à–∞ —Ñ–∞–Ω—Ç–∞–∑–∏—è!\nüíé–û—Ç–∑—ã–≤—á–∏–≤–∞—è –∏ –¥—Ä—É–∂–µ–ª—é–±–Ω–∞—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è!\nüíé–ù–∞—à —Å–µ—Ä–≤–µ—Ä —Ä–∞–±–æ—Ç–∞–µ—Ç –Ω–∞ —Å–≤–µ—Ä—Ö–º–æ—â–Ω–æ–º –∂–µ–ª–µ–∑–µ —Å–æ —Å—Ç–∞–±–∏–ª—å–Ω—ã–º —Ç–∏–∫—Ä–µ–π—Ç–æ–º –≤ 60!\nüíé–ü–æ–ª–Ω–∞—è –ª–æ–∫–∞–ª–∏–∑–∞—Ü–∏—è –∏ –ø–æ—Å—Ç–æ—è–Ω–Ω—ã–µ –æ–±–Ω–æ–≤–ª–µ–Ω–∏—è!\n"
cryo_sleep_rejoining = true

[shuttle]
auto_call_time = 960
auto_call_extension_time = 30

[atmos]
space_wind_max_velocity = 22.0

[salvage]
expedition_failed_cooldown = 600.0

[replay]
client_recording_enabled = false

[viewport]
maximum_width = 26

[server]
id = "frontier_main"
rules_file = "FrontierRuleset"

[infolinks]
bug_report = "https://github.com/Apxumekm0p/Eclipse-New-Frontier/issues/new/choose"
discord    = "https://discord.gg/5J9Q8WuJFd"
#forum      = ""
github     = "https://github.com/Apxumekm0p/Eclipse-New-Frontier"
#patreon    = ""
#website    = ""
#wiki       = ""
#appeal     = ""

[nf14]
publictransit.wait_time = 60.0
respawn.time = 300.0

[eclipse]
restart_when_server_empty = false
start_round_with_no_players = true
shuttle_auto_call_enabled = false

[discord]
rich_main_icon_id = "https://shorturl.at/nHmHm"
