- type: latheRecipePack
  id: NFServiceStorageStatic
  recipes:
  - NFBoxMREEmpty
  - NFHappyHonkEmpty
  - NFHappyHonkMimeEmpty
  - NFFoodBoxPizza
  - NFFoodBoxDonutEmpty
  - NFFoodBoxNuggetEmpty
  - NFFoodContainerEggEmpty
  - NFFoodBoxSushi
  - DrinkKegSteel
  - DrinkKegPlastic
  - DrinkKegWood
  - Jug
  - LargeBeaker

- type: latheRecipePack
  id: NFBotanyToolsStatic
  recipes:
  - PlantBGoneSprayEmpty
  - WeedSprayEmpty
  - PestSprayEmpty
  - HydroponicsToolMiniHoe
  - HydroponicsToolScythe
  - HydroponicsToolHatchet
  - HydroponicsToolSpade
  - HydroponicsToolClippers
  - ServiceSelectiveDropper
  - DiseaseSwab
  - PlantBag
  - Shovel

- type: latheRecipePack
  id: NFServiceEvaPackStatic
  recipes:
  - ClothingOuterEVASuitHydro
  - ClothingOuterEVASuitJanitor
  - ClothingOuterEVASuitServiceWorker
  - ClothingOuterEVASuitChaplain
  - ClothingOuterEVASuitBoxerRed
  - ClothingOuterEVASuitBoxerGreen
  - ClothingOuterEVASuitBoxerBlue
  - ClothingOuterEVASuitBoxerYellow

- type: latheRecipePack
  id: NFServiceKitchenStatic
  recipes:
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkIceBucketEmpty
  - KitchenKnife
  - ButchCleaver
  - ServiceRollingPin
  - ServiceSpoon
  - ServiceFork
  - ServicePairedChopsticks
  - FoodBowlBig
  - FoodPlate
  - FoodPlateSmall
  - FoodPlateMuffinTin
  - FoodPlateTin
  - FoodKebabSkewer
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - NapkinDrum
  - Napkin
  - CondimentCupDispenser
  - CondimentCup
  - FoodCondimentSqueezeBottleClear
  - FoodFrozenPopsicleTrash
  - DrinkWaterCup
  - DrinkDisposableCup #imp
  - FreezerElectronics
  - Syringe

- type: latheRecipePack
  id: NFServiceStatic
  recipes:
  - DeskBell
  - BrbSign
  - WetFloorSign
  - Holoprojector
  - MailCapsule
  - Mousetrap
  - PillCanister
  - ChemistryEmptyBottle01

- type: latheRecipePack
  id: NFPaperAndPaperAccessories
  recipes:
  - NFMaterialCardboard1Processed
  - NFSheetPaperFromWood
  - NFSheetPaperFromCardboard
  - PaperFromSheetPaper

- type: latheRecipePack
  id: NFServiceBoardsStatic
  recipes:
  - CondimentDispenserCircuitboard
  - ImpCoffeeMachineCircuitboard #imp

- type: latheRecipePack
  id: NFLightsColoredStatic
  recipes:
  - LightBulbCrystalGreen
  - LightBulbCrystalRed
  - LightBulbCrystalBlack
  - LightBulbCrystalOrange
  - LightBulbCrystalPink
  - LightBulbCrystalYellow
  - LightBulbCrystalBlue
  - LightBulbCrystalCyan
  - LightTubeCrystalGreen
  - LightTubeCrystalRed
  - LightTubeCrystalBlack
  - LightTubeCrystalOrange
  - LightTubeCrystalPink
  - LightTubeCrystalYellow
  - LightTubeCrystalBlue
  - LightTubeCrystalCyan
  - LightTubeUltraviolet


- type: latheRecipePack
  id: NFServiceArchetypeStatic
  recipes:
  - BorgModuleAdvancedCleaning
  - PortablePumpMachineCircuitBoard
  - MegaSprayBottle
  - ServiceSelectiveDropper
  - PlantAnalyzer
  - HotplateMachineCircuitboard

- type: latheRecipePack
  id: NFServiceTechfabEmagStatic
  recipes:
    - NFHappyHonkNukieEmpty
    - NFHappyHonkCluwneEmpty

  # Begin McFab

- type: latheRecipePack
  id: NFMcServiceTechfabStatic
  recipes:
    - MysteryFigureBox
    - SpaceBladeMc
    - NFHappyHonkMcCargoEmpty
    - ClothingHeadHatMcCrown
    - CigPackMcCargo
    - DrinkDisposableMcCup #imp

# End McFab

- type: latheRecipePack
  id: NFServiceBoards
  recipes:
  - KitchenAssemblerMachineCircuitboard # Frontier
  - ElectricRangeMachineCircuitboard # Frontier
  - ImpCoffeeMachineCircuitboard # Frontier
  - ReagentGrinderMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - BiogeneratorMachineCircuitboard
  - DeepFryerMachineCircuitboard
  - PortablePumpMachineCircuitBoard

- type: latheRecipePack
  id: NFService
  recipes:
  - ServiceSelectiveDropper # Frontier
  - PlantAnalyzer # Frontier
  - JanicartFlatpack # Frontier
  - PlantBagOfHolding # Delta-V
