- type: latheRecipePack
  id: NFServiceStorage
  recipes:
  - NFBoxMREEmpty
  - NFHappyHonkEmpty
  - NFHappyHonkMimeEmpty
  - NFHappyHonkMcCargoEmpty
  - NFFoodBoxPizza
  - NFFoodBoxDonutEmpty
  - NFFoodBoxNuggetEmpty
  - NFFoodContainerEggEmpty
  - NFFoodBoxSushi
  - DrinkKegSteel
  - DrinkKegPlastic
  - DrinkKegWood

- type: latheRecipePack
  id: NFServiceStatic
  recipes:
  - Durathread # Frontier
  - FoodCondimentSqueezeBottleClear # Frontier

- type: latheRecipePack
  id: NFService
  recipes:
  - ServiceSelectiveDropper # Frontier
  - PlantAnalyzer # Frontier
  - JanicartFlatpack # Frontier
  - PlantBagOfHolding # Delta-V

- type: latheRecipePack
  id: NFServiceBoardsStatic
  recipes:
  - CondimentDispenserCircuitboard
  - ImpCoffeeMachineCircuitboard #imp

- type: latheRecipePack
  id: NFServiceBoards
  recipes:
  - KitchenAssemblerMachineCircuitboard # Frontier
  - ElectricRangeMachineCircuitboard # Frontier
  - ImpCoffeeMachineCircuitboard # Frontier
  - ReagentGrinderMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - BiogeneratorMachineCircuitboard
  - DeepFryerMachineCircuitboard
  - PortablePumpMachineCircuitBoard

- type: latheRecipePack
  id: NFPaperAndPaperAccessories
  recipes:
  - NFMaterialCardboard1Processed
  - NFSheetPaperFromWood
  - NFSheetPaperFromCardboard
