# Base dungeon prototypes
- type: dungeonConfig
  id: Everything
  layers:
  - !type:PrefabDunGen
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall

  - !type:CorridorDunGen
    width: 3
  
  - !type:DungeonEntranceDunGen
    count: 2

  - !type:RoomEntranceDunGen

  - !type:EntranceFlankDunGen

  - !type:ExternalWindowDunGen

  - !type:WallMountDunGen

  - !type:BoundaryWallDunGen

  - !type:JunctionDunGen
    width: 1

  - !type:JunctionDunGen

  - !type:AutoCablingDunGen

  - !type:CornerClutterDunGen

  data:
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Walls: WallSolid
    spawnGroups:
      CornerClutter: BaseClutterNF
      Entrance: BaseAirlockNF
      EntranceFlank: BaseWindowNF
      Junction: BaseAirlockNF
      WallMounts: BaseWallMountsNF
      Window: BaseWindowNF
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - CaveFactory
        - LavaBrig
        - LavaMercenary
        - SalvageExperiment
        - VirologyLab
        - SalvageOutpost

- type: entitySpawnEntry
  id: BaseClutterNF
  entries:
  - id: PottedPlantRandom
    amount: 1

- type: entitySpawnEntry
  id: BaseAirlockNF
  entries:
  - id: CableApcExtension
  - id: AirlockGlassDungeon

- type: entitySpawnEntry
  id: BaseWindowNF
  entries:
  - id: GrilleDungeon
  - id: WindowDungeon

- type: entitySpawnEntry
  id: BaseWallMountsNF
  entries:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content
    - id: DefibrillatorCabinetFilled
      prob: 0.1
      orGroup: content

# CaveFactory prototypes
- type: dungeonConfig
  id: CaveFactory
  data:
    colors:
      Decals: "#ffa64d96"
    spawnGroups:
      WallMounts: CaveFactoryWallMountsNF
    whitelists:
      Rooms:
        tags:
          - CaveFactory

  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: CaveFactoryWallMountsNF
  entries:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

# MedSci prototypes
- type: dungeonConfig
  id: MedSci
  data:
    spawnGroups:
      WallMounts: MedSciWallMountsNF
    whitelists:
      Rooms:
        tags:
          - SalvageExperiment

  layers:
  - !type:PrototypeDunGen
    proto: Everything

- type: entitySpawnEntry
  id: MedSciWallMountsNF
  entries:
    - id: RandomPosterLegit
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content
    - id: DefibrillatorCabinetFilled
      prob: 0.2
      orGroup: content

# FactoryDorms prototypes
- type: dungeonConfig
  id: FactoryDorms
  data:
    whitelists:
      Rooms:
        tags:
          - CaveFactory
  layers:
  - !type:PrototypeDunGen
    proto: Everything

# LavaMercenary prototypes
- type: dungeonConfig
  id: LavaMercenary
  data:
    colors:
      Decals: "#5E7C16"
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Walls: WallSolid
    spawnGroups:
      CornerClutter: BaseClutter
      Entrance: MercenaryAirlockNF
      EntranceFlank: BaseWindow
      Junction: MercenaryAirlockNF
      WallMounts: LavaMercenaryWallMountsNF
      Window: BaseWindow
    whitelists:
      Rooms:
        tags:
          - LavaMercenary
  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: MercenaryAirlockNF
  entries:
    - id: CableApcExtension
    - id: AirlockMercenaryGlassDungeon

- type: entitySpawnEntry
  id: LavaMercenaryWallMountsNF
  entries:
    # Posters
    - id: RandomPosterContraband
      orGroup: content
    - id: ExtinguisherCabinetFilled
      prob: 0.2
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

# VirologyLab prototypes
- type: dungeonConfig
  id: VirologyLab
  data:
    colors:
      Decals: "#467b41"
    spawnGroups:
      Entrance: VirologyAirlockNF
    whitelists:
      Rooms:
        tags:
          - VirologyLab

  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: VirologyAirlockNF
  entries:
    - id: CableApcExtension
    - id: AirlockVirologyGlassDungeon

# SalvageOutpost prototypes
- type: dungeonConfig
  id: SalvageOutpost
  data:
    colors:
      Decals: "#9A54BF"
    entities:
      CornerWalls: WallMining
      Walls: WallMining
    spawnGroups:
      Entrance: MiningAirlockNF
      EntranceFlank: MiningWindowNF
      Window: MiningWindowNF
    whitelists:
      Rooms:
        tags:
          - SalvageOutpost
  layers:
  - !type:PrototypeDunGen
    proto: Everything

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entitySpawnEntry
  id: MiningAirlockNF
  entries:
    - id: CableApcExtension
    - id: AirlockMiningGlassDungeon

- type: entitySpawnEntry
  id: MiningWindowNF
  entries:
    - id: GrilleDungeon
    - id: MiningWindowDungeon

## Wallmounts
- type: entitySpawnEntry
  id: NanoTrasenFacilityWallmounts
  entries:
  - id: RandomPosterLegit
    orGroup: content
  - id: ExtinguisherCabinetFilled
    prob: 0.2
    orGroup: content
  - id: IntercomCommon
    prob: 0.1
    orGroup: content
  - id: DefibrillatorCabinetFilled
    prob: 0.05
    orGroup: content
