- type: latheRecipe
  id: ServiceRollingPin
  result: RollingPin
  completetime: 1
  materials:
    Wood: 200

- type: latheRecipe
  id: ServiceSpoon
  result: Spoon
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: ServiceFork
  result: Fork
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: ServicePairedChopsticks
  result: PairedChopsticks
  completetime: 1
  materials:
    Glass: 100

- type: latheRecipe
  id: ServiceFoodBowlBig
  result: FoodBowlBig
  completetime: 1
  materials:
    Glass: 100

- type: latheRecipe
  id: ServiceFoodPlate
  result: FoodPlate
  completetime: 1
  materials:
    Glass: 150

- type: latheRecipe
  id: ServiceFoodPlateSmall
  result: FoodPlateSmall
  completetime: 1
  materials:
    Glass: 75

- type: latheRecipe
  id: ServiceFoodPlateTin
  result: FoodPlateTin
  completetime: 1
  materials:
    Steel: 150

- type: latheRecipe
  id: ServiceFoodKebabSkewer
  result: FoodKebabSkewer
  completetime: 1
  materials:
    Steel: 75
