- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600
  startingGear: PrisonGuardGear
  icon: "JobIconWarden" 
  supervisors: job-supervisors-hos # Frontier
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service # Frontier
  - External # Frontier
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: PrisonGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    outerClothing: ClothingOuterArmorBasic # Frontier
    id: GuardPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal # Frontier
    gloves: ClothingHandsGlovesCombat # Frontier
  innerClothingSkirt: ClothingUniformJumpsuitPrisonGuard
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
