- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
  startingGear: PrisonGuardGear
  canBeAntag: false
  icon: "JobIconWarden" 
  supervisors: job-supervisors-warden
  setPreference: true
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: PrisonGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    id: GuardPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpsuitPrisonGuard
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
