- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-name-mail-carrier
  startingGear: MailCarrierGear
  playTimeTracker: JobMailCarrier
  icon: "JobIconMailCarrier"
  supervisors: "station representative"
  access:
  - Cargo
  - Maintenance
  - Service

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadMailCarrier
    jumpsuit: ClothingUniformJumpsuitMailCarrier
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
  innerClothingSkirt: ClothingUniformJumpskirtMailCarrier
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
