- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
<<<<<<< HEAD
    belt: NFWeaponPistolN1984 # Frontier
    pocket1: BoxFolderBlack
=======
    belt: WeaponPistolN1984
    pocket1: BoxFolderCentComClipboardThreePapers
>>>>>>> e917c8e067e70fa369bf8f1f393a465dc51caee8
    pocket2: PenCentcom


- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
