- type: job
  id: Gladiator
  name: job-name-gladiator
  description: job-description-gladiator
  playTimeTracker: JobGladiator
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: GladiatorGear
  canBeAntag: false
  icon: "JobIconBoxer"
  supervisors: job-supervisors-security
  access:
  - Service
  - Maintenance
  - External # Frontier
