- type: job
  id: MartialArtist
  name: job-name-martialartist
  description: job-description-martialartist
  playTimeTracker: JobMartialArtist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MartialGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - External # Frontier

- type: startingGear
  id: MartialGear
  equipment:
    jumpsuit: ClothingUniformMartialGi
    belt: ClothingBeltMartialBlack
    back: ClothingBackpackFilled
    id: MartialArtistPDA
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesWizard
    gloves: ClothingHandsGlovesBoxingRed
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
