- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-name-mail-carrier
  startingGear: MailCarrierGear
  alwaysUseSpawner: true
  playTimeTracker: JobMailCarrier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-sr
  weight: 90 # Frontier
  displayWeight: 30 # Frontier
  canBeAntag: false
  access:
  - External # Frontier
  - Maintenance
  - Service
  - Mail # Frontier
  - Frontier # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadMailCarrier
    eyes: ClothingEyesHudMail
    id: CourierPDA
#    ears: ClothingHeadsetService # Frontier - ClothingHeadsetCargo<ClothingHeadsetService
    belt: MailBag
  storage:
    back:
    - EncryptionKeyService # Frontier
    - HandheldCrewMonitor # Frontier
    - ShipVoucherFrontierMailCarrier # Frontier