- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassengerOld
  setPreference: false # Frontier
  startingGear: PassengerGear
  icon: "JobIconPassenger"
#  supervisors: job-supervisors-everyone
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
