- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
