- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: BotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff
