- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: ProfessionalChef #Nyano - End Summary.

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
