- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: JanitorGear
  alwaysUseSpawner: true
  icon: JobIconNFJanitor # Frontier: JobIconJanitor<JobIconNFJanitor
  supervisors: job-supervisors-sr
  canBeAntag: false
  access:
  - Service
  - Janitor
  - Maintenance
  - External # Frontier
  - Frontier # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorNFPDA # Frontier: JanitorPDA<JanitorNFPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - BoxSurvival

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
