- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: JanitorGear
  alwaysUseSpawner: true
  icon: "JobIconJanitor"
  supervisors: job-supervisors-sr
  weight: 100 # Frontier
  displayWeight: 40 # Frontier
  canBeAntag: false
  access:
  - Service
  - Janitor
  - Maintenance
  - External # Frontier
  - Frontier # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - ShipVoucherFrontierJanitor # Frontier

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
