- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 # 2.5 hrs
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hire
  canBeAntag: false
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
