- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Brig
  - Maintenance
  - External # Frontier

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled # Frontier
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: HyperlinkBookSpaceLaw # Frontier
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled # Frontier
  duffelbag: ClothingBackpackDuffelLawyerFilled # Frontier
