- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - External # Frontier

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackLibrarianFilled
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
    pocket2: HandLabeler # for making named bestsellers
  innerClothingSkirt: ClothingUniformJumpskirtLibrarian
  satchel: ClothingBackpackSatchelLibrarianFilled
  duffelbag: ClothingBackpackDuffelLibrarianFilled
