- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
    - type: FrenchAccent

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    id: MimePDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
    event: !type:InvisibleWallActionEvent
