- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  - External # Frontier
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
