- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 1800 #0.5 hr
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # access: # Frontier
  # - Service # Frontier
  # - Maintenance # Frontier
  # - Bar # Frontier
  # - Kitchen # Frontier
  # extendedAccess: # Frontier
  # - Hydroponics # Frontier

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ServiceWorkerChameleonOutfit
  job: ServiceWorker
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
