- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ValetGear
  alwaysUseSpawner: true
  icon: "JobIconValet" # Frontier: JobIconServiceWorker<JobIconValet
  supervisors: job-supervisors-sr
  weight: 60 # Frontier
  displayWeight: 10 # Frontier
  canBeAntag: false
  access:
  - Maintenance
  - External # Frontier
  - Service
  - Frontier # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
  # jumpsuit: ClothingUniformJumpsuitValet
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
    id: ValetPDA
#    ears: ClothingHeadsetService # Frontier
  # innerClothingSkirt: ClothingUniformJumpskirtValet
  # satchel: ClothingBackpackSatchelFilled
  # duffelbag: ClothingBackpackDuffelFilled
  # messenger: ClothingBackpackMessengerFilled # Frontier
  storage: # Frontier
    back: # Frontier
    - EncryptionKeyService # Frontier
    - ShipVoucherFrontierValet # Frontier
