- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hrs as sec
  canBeAntag: false
  icon: "JobIconStc" 
  supervisors: job-supervisors-sr
  setPreference: true
  access:
  - Service
  - Maintenance
  - External
  - Frontier
  - StationTrafficController

- type: startingGear
  id: StcGear
  equipment:
    id: StcPDA
    ears: ClothingHeadsetAltCommand
    pocket1: RubberStampStc
