- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hrs as sec
  canBeAntag: false
  icon: "JobIconStc" 
  supervisors: job-supervisors-hop
  setPreference: true
  access:
  - Maintenance
  - External
  - Frontier

- type: startingGear
  id: StcGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetectiveGrey
    back: ClothingBackpackStcFilled
    shoes: ClothingShoesColorBlack
    id: StcPDA
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  innerClothingSkirt: ClothingUniformJumpskirtDetectiveGrey
  satchel: ClothingBackpackSatchelStcFilled
  duffelbag: ClothingBackpackDuffelStcFilled
