- type: accessLevel
  id: Mercenary
  name: id-card-access-level-mercenary

- type: accessLevel
  id: Sergeant
  name: id-card-access-level-sergeant
  
- type: accessLevel
  id: Bailiff
  name: id-card-access-level-bailiff
  
- type: accessGroup
  id: CadetNfsdAccess
  tags:
  - Maintenance
  - External
  - Security
  - Brig
  
- type: accessGroup
  id: GeneralNfsdAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary # Frontier
  - Captain # Frontier

- type: accessGroup
  id: GeneralNfsdBrigAccess
  tags:
  - Maintenance
  - External
  - Brig
