[game]
hostname = "[EN][MRP] Frontier | Hypatia [US 1]"
soft_max_players = 120

[shuttle]
auto_call_time = 720 # 12 hours

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"

[nf14.scheduled_roundend]
active = true
minimum_duration = 240
roundend_times = """
0 9 * * 0
0 19 * * 0
0 5 * * 1
0 15 * * 1
0 1 * * 2
0 11 * * 2
0 21 * * 2
0 7 * * 3
0 16 * * 3
0 1 * * 4
0 11 * * 4
0 21 * * 4
0 7 * * 5
0 17 * * 5
0 3 * * 6
0 13 * * 6
0 23 * * 6
"""