- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-hire # Frontier
  jobEntity: PlayerBorgGeneric