# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 5h
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-hire # Frontier: rd<hire
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
  setPreference: false # Frontier

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
<<<<<<< HEAD
      time: 43200 # 12 hrs # Frontier: 10<12 hrs
=======
      time: 10h
>>>>>>> e917c8e067e70fa369bf8f1f393a465dc51caee8
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-hire # Frontier
  jobEntity: PlayerBorgBattery
  applyTraits: false
