- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  setPreference: false # Frontier
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Science
    time: 10h
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  ## Frontier: commented stuff below out
  # access:
  # - Research
  # - Command
  # - Maintenance
  # - ResearchDirector
  # - Brig
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
  #   components:
  #     - type: CommandStaff
  ## End Frontier: commented stuff above out
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
