- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Science
#      time: 10800
#      inverted: true # stop playing intern if you're good at science!
    - !type:OverallPlaytimeRequirement # Frontier
      time: 10800 # Frontier
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: false
  access:
  - Research
  - Maintenance
  - External # Frontier
  setPreference: false # Frontier

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff
