- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-head-objective
  # guides: [ Revolutionaries ] # Frontier: removed, irrelevant
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  # guides: [ Revolutionaries ] # Frontier: removed, irrelevant

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
