- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: false
  objective: roles-antag-thief-objective

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ToolboxThief
    - ClothingHandsChameleonThief
    - ThiefBeacon