- type: antag
  id: Survivor
  name: roles-antag-survivor-name
  antagonist: true
  objective: roles-antag-survivor-objective
  # guides: [  ]

- type: antag
  id: Wizard
  name: roles-antag-wizard-name
  antagonist: true
  # setPreference: true # Frontier
  objective: roles-antag-wizard-objective # TODO: maybe give random objs and stationary ones from AntagObjectives and AntagRandomObjectives
  requirements: # I hate time locked roles but this should be enough time for someone to be acclimated
  - !type:OverallPlaytimeRequirement
<<<<<<< HEAD
    time: 18000 # 5h
  # guides: [ Wizard ] # Frontier: no wizard guidebook page
=======
    time: 5h
  guides: [ Wizard ]
>>>>>>> e917c8e067e70fa369bf8f1f393a465dc51caee8

# See wizard_startinggear for wiz start gear options
