- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      # - id: WeaponDisabler # Frontier
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler # Frontier
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler # Frontier
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: BookSpaceLaw
        prob: 0.5

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesNoir
      - id: ClothingHeadHatDetGadget
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetectiveLoadout
      - id: FlippoEngravedLighter
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler
      - id: BoxTapeRecorder # DeltaV
        prob: 0.3

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool
        prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseC1Contraband ] # Frontier: BaseSecurityContraband<BaseC1Contraband
  id: GunSafeDisabler
  name: disabler safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
      amount: 5 # Frontier

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafePistolMk58
  name: mk58 safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponPistolMk58 # Frontier: WeaponPistolMk58<NFWeaponPistolMk58
      amount: 4
    - id: NFMagazinePistol35 # Frontier: MagazinePistol<NFMagazinePistol35
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeRifleLecter
  name: Lecter safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponRifleAssaultLecter # Frontier: WeaponRifleLecter<NFWeaponRifleAssaultLecter
      amount: 2
    - id: NFMagazineRifle20 # Frontier: MagazineRifle<NFMagazineRifle20
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeSubMachineGunDrozd
  name: Drozd safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponSubMachineGunDrozd # Frontier: WeaponSubMachineGunDrozd<NFWeaponSubMachineGunDrozd
      amount: 2
    - id: NFMagazineSubMachineGun35 # Frontier: MagazinePistolSubMachineGun<NFMagazineSubMachineGun35
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunEnforcer
  name: Enforcer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponShotgunEnforcer # Frontier: WeaponShotgunEnforcer<NFWeaponShotgunEnforcer
      amount: 2
    - id: NFAmmunitionBoxShellShotgunBuckshot # Frontier: BoxLethalshot<NFAmmunitionBoxShellShotgunBuckshot
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunKammerer
  name: Kammerer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponShotgunKammerer # Frontier: WeaponShotgunKammerer<NFWeaponShotgunKammerer
      amount: 2
    - id: NFAmmunitionBoxShellShotgunBuckshot # Frontier: BoxLethalshot<NFAmmunitionBoxShellShotgunBuckshot
      amount: 2

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  name: WT-550 safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponSubMachineGunWt550 # Frontier: WeaponSubMachineGunWt550<NFWeaponSubMachineGunWt550
      amount: 2
    - id: NFMagazineSubMachineGunTopMounted35 # Frontier: MagazinePistolSubMachineGunTopMounted<NFMagazineSubmachineGunTopMounted35
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure] # Frontier: remove BaseSecurityContraband
  id: GunSafeLaserCarbine
  name: laser safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
    - id: NFWeaponEnergyRifleCarbine # Frontier: WeaponLaserCarbine<NFWeaponEnergyRifleCarbine
      amount: 3
