- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
#      - id: FlashlightSeclite # Frontier
#      - id: WeaponDisabler
      - id: ClothingHeadHatWarden
      - id: ClothingHeadHatBeretWarden
#      - id: ClothingBeltSecurityFilled
#      - id: Flash
#      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurityWarden # Frontier
#      - id: ClothingHandsGlovesCombat
#      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: ClothingShoesBootsWinterWarden # Frontier
      - id: RubberStampWarden
#      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
#      - id: HoloprojectorSecurity # Frontier - Starting gear
#      - id: ClothingEyesHudSecurity
#      - id: NitrogenTankFilled
#      - id: OxygenTankFilled
      - id: AirTankFilled
      - id: ClothingMaskGasSecurity # Frontier
      - id: JetpackSecurityFilled # Frontier
      - id: HandheldGPSBasic # Frontier
      - id: ClothingShoesBootsMagCombatFilled # Frontier

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
#      - id: FlashlightSeclite
#      - id: WeaponDisabler
      - id: ClothingHeadHatWarden
      - id: ClothingHeadHatBeretWarden
#      - id: ClothingBeltSecurityFilled
#      - id: Flash
#      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurityWarden # Frontier
#      - id: ClothingHandsGlovesCombat
#      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
#      - id: DoorRemoteArmory
#      - id: HoloprojectorSecurity # Frontier - Starting gear
#      - id: ClothingEyesHudSecurity

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
#      - id: FlashlightSeclite
#      - id: ClothingUniformJumpsuitSecGrey
#        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
#      - id: ClothingBeltSecurityFilled
#      - id: Flash
#      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecuritySafe # Ask SR or Sheriff for keys
#      - id: ClothingHandsGlovesColorBlack
#      - id: ClothingShoesBootsJack
#      - id: WeaponMeleeNeedle
#        prob: 0.1
#      - id: ClothingEyesHudSecurity

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
#      - id: ClothingEyesHudSecurity
#      - id: ClothingHeadHatFedoraBrown
#      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
#      - id: ClothingOuterCoatDetective
#      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
#        prob: 0.9 # Frontier - Always has this
      - id: Screwdriver
#        prob: 0.9 # Frontier - Always has this
      - id: Multitool
#        prob: 0.5 # Frontier - Always has this

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3
