- type: department
  id: Frontier
  description: department-Frontier-description
  color: "#334E6D"
  weight: 90
  roles:
  - StationRepresentative # Frontier
  - StationTrafficController # Frontier
  - Valet # nyano
  - Janitor
  - MailCarrier # nyano
  - SecurityGuard
  enabled: true
