- type: latheRecipe     #Vector
  id: MagazineVector45
  result: MagazineVector45
  category: Ammo
  completetime: 5
  materials:
     Steel: 260

- type: latheRecipe     #Vector
  id: MagazineVector45Empty
  result: MagazineVector45Empty
  category: Ammo
  completetime: 5
  materials:
     Steel: 110

- type: latheRecipe     #Vector
  id: MagazineVector22
  result: MagazineVector22
  category: Ammo
  completetime: 5
  materials:
     Steel: 240

- type: latheRecipe     #Vector
  id: MagazineVector22Incendiary
  result: MagazineVector22Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 200
     Plastic: 400

- type: latheRecipe     #Vector
  id: MagazineVector22Practice
  result: MagazineVector22Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 230
     Plastic: 160

- type: latheRecipe     #Vector
  id: MagazineVector22Uranium
  result: MagazineVector22Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 320
     Uranium: 320

- type: latheRecipe     #Vector
  id: MagazineVector22Empty
  result: MagazineVector22Empty
  category: Ammo
  completetime: 5
  materials:
     Steel: 150

- type: latheRecipe     #Vector
  id: MagazineBoxVector22
  result: MagazineBoxVector22
  category: Ammo
  completetime: 5
  materials:
     Steel: 240

- type: latheRecipe     #Vector
  id: MagazineBoxVector22Incendiary
  result: MagazineBoxVector22Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 450
     Plastic: 900

- type: latheRecipe     #Vector
  id: MagazineBoxVector22Practice
  result: MagazineBoxVector22Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 500
     Plastic: 380

- type: latheRecipe     #Vector
  id: MagazineBoxVector22Uranium
  result: MagazineBoxVector22Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 650
     Uranium: 650

- type: latheRecipe     #Vector
  id: MagazineBoxVector45
  result: MagazineBoxVector45
  category: Ammo
  completetime: 5
  materials:
     Steel: 450

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Uranium
  result: MagazineBoxVector45Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 580
     Uranium: 580

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Incendiary
  result: MagazineBoxVector45Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 340
     Plastic: 800

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Practice
  result: MagazineBoxVector45Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 410
     Plastic: 310

- type: latheRecipe     #Vector
  id: MagazineVector45Practice
  result: MagazineVector45Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 160
     Plastic: 160

- type: latheRecipe     #Vector
  id: MagazineVector45Incendiary
  result: MagazineVector45Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 180
     Plastic: 450

- type: latheRecipe     #Vector
  id: MagazineVector45Uranium
  result: MagazineVector45Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 300
     Uranium: 300

- type: latheRecipe     #ShuttleGuns
  id: ShuttleShotgunMachineCircuitboard
  result: ShuttleShotgunMachineCircuitboard
  completetime: 5
  materials:
     Steel: 1700
     Glass: 1100
     Gold: 400

- type: latheRecipe     #ShuttleGuns
  id: ShuttleGunAntiMaterialMachineCircuitboard
  result: ShuttleGunAntiMaterialMachineCircuitboard
  completetime: 13
  materials:
     Steel: 3100
     Glass: 2500
     Gold: 1600

- type: latheRecipe     #ShuttleGuns
  id: ShuttleLightRifleGunMachineCircuitboard
  result: ShuttleLightRifleGunMachineCircuitboard
  completetime: 7
  materials:
     Steel: 2400
     Glass: 1800
     Gold: 900

- type: latheRecipe     #ShuttleGuns
  id: ShuttleSMGRifleMachineCircuitboard
  result: ShuttleSMGRifleMachineCircuitboard
  completetime: 4
  materials:
     Steel: 1300
     Glass: 800
     Gold: 400

- type: latheRecipe     #ShuttleGuns
  id: ShuttleMagnumRifleMachineCircuitboard
  result: ShuttleMagnumRifleMachineCircuitboard
  completetime: 9
  materials:
     Steel: 2200
     Glass: 1700
     Gold: 1000

- type: latheRecipe     #ShuttleGuns
  id: ShuttleShotgunShellsBox
  result: ShuttleShotgunShellsBox
  completetime: 6
  materials:
     Steel: 600
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  id: ShuttleSmgRifleAmmoBox
  result: ShuttleSmgRifleAmmoBox
  completetime: 10
  materials:
     Steel: 1300
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  id: ShuttleRifleAmmoBox
  result: ShuttleRifleAmmoBox
  completetime: 15
  materials:
     Steel: 2700
     Plastic: 300

- type: latheRecipe     #ShuttleGuns
  id: ShuttleMagnumRifleAmmoBox
  result: ShuttleMagnumRifleAmmoBox
  completetime: 8
  materials:
     Steel: 900
     Plastic: 300
