- type: latheRecipe     #Vector
  id: MagazineVector45
  result: MagazineVector45
  category: Ammo
  completetime: 5
  materials:
     Steel: 260

- type: latheRecipe     #Vector
  id: MagazineVector45Empty
  result: MagazineVector45Empty
  category: Ammo
  completetime: 5
  materials:
     Steel: 110

- type: latheRecipe     #Vector
  id: MagazineVector22
  result: MagazineVector22
  category: Ammo
  completetime: 5
  materials:
     Steel: 240

- type: latheRecipe     #Vector
  id: MagazineVector22Empty
  result: MagazineVector22Empty
  category: Ammo
  completetime: 5
  materials:
     Steel: 150

- type: latheRecipe     #Vector
  id: MagazineBoxVector22
  result: MagazineBoxVector22
  category: Ammo
  completetime: 5
  materials:
     Steel: 240

- type: latheRecipe     #Vector
  id: MagazineBoxVector45
  result: MagazineBoxVector45
  category: Ammo
  completetime: 5
  materials:
     Steel: 450

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Uranium
  result: MagazineBoxVector45Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 580
     Uranium: 580

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Incendiary
  result: MagazineBoxVector45Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 340
     Plastic: 800

- type: latheRecipe     #Vector
  id: MagazineBoxVector45Practice
  result: MagazineBoxVector45Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 410
     Plastic: 310

- type: latheRecipe     #Vector
  id: MagazineVector45Practice
  result: MagazineVector45Practice
  category: Ammo
  completetime: 5
  materials:
     Steel: 160
     Plastic: 160

- type: latheRecipe     #Vector
  id: MagazineVector45Incendiary
  result: MagazineVector45Incendiary
  category: Ammo
  completetime: 5
  materials:
     Steel: 180
     Plastic: 450

- type: latheRecipe     #Vector
  id: MagazineVector45Uranium
  result: MagazineVector45Uranium
  category: Ammo
  completetime: 5
  materials:
     Steel: 300
     Uranium: 300
