- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary" 
  supervisors: job-supervisors-captain
  setPreference: true
  access:
  - Maintenance
  - External
  - Mercenary

- type: startingGear
  id: MercenaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    back: ClothingBackpackMercenaryFilled
    shoes: ClothingShoesBootsMercenaryFilled
    mask: ClothingMaskGasMercenary
    eyes: ClothingEyesGlassesMercenary
    gloves: ClothingHandsMercGlovesCombat
    head: ClothingHeadHatBeretMerc
    outerClothing: ClothingOuterVestWebMerc
    id: MercenaryPDA
    ears: ClothingHeadsetGrey
    belt: ClothingBeltMercWebbing
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpsuitMercenary
  satchel: ClothingSatchelMercenaryFilled
  duffelbag: ClothingDuffelbagMercenaryFilled
