## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes: [] # Frontier
  # - ClothingEyesHudSecurity # Frontier
  # - ForensicPad # Frontier
  # - Handcuffs # Frontier
  # - TargetClown # Frontier
  # - TargetHuman # Frontier
  # - TargetSyndicate # Frontier
  # - Zipties # Frontier

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  # Frontier: empty set
  recipes: []
  # - BoxShotgunPractice
  # - MagazineBoxLightRiflePractice
  # - MagazineBoxMagnumPractice
  # - MagazineBoxPistolPractice
  # - MagazineBoxRiflePractice
  # - WeaponDisablerPractice
  # - WeaponLaserCarbinePractice
  # - MagazineLightRiflePractice
  # - MagazineRiflePractice
  # - MagazinePistolPractice
  # - SpeedLoaderMagnumPractice
  # - MagazinePistolSubMachineGunPractice
  # - WeaponFlareGunSecurity
  # End Frontier

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes: [] # Frontier
  # - BoxLethalshot # Frontier
  # - BoxShotgunSlug # Frontier
  # - MagazineBoxLightRifle # Frontier
  # - MagazineBoxMagnum # Frontier
  # - MagazineBoxPistol # Frontier
  # - MagazineBoxRifle # Frontier
  # - MagazineLightRifle # Frontier
  # - MagazineLightRifleEmpty # Frontier
  # - MagazinePistol # Frontier
  # - MagazinePistolEmpty # Frontier
  # - MagazinePistolSubMachineGun # Frontier
  # - MagazinePistolSubMachineGunEmpty # Frontier
  # - MagazinePistolSubMachineGunTopMounted # Frontier
  # - MagazinePistolSubMachineGunTopMountedEmpty # Frontier
  # - MagazineRifle # Frontier
  # - MagazineRifleEmpty # Frontier
  # - MagazineShotgun # Frontier
  # - MagazineShotgunEmpty # Frontier
  # - MagazineShotgunSlug # Frontier
  # - SpeedLoaderMagnum # Frontier
  # - SpeedLoaderMagnumEmpty # Frontier

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes: [] # Frontier
  # - Flash # Frontier
  # - Stunbaton # Frontier
  # - CombatKnife # Frontier
  # - RiotShield # Frontier

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - NFClothingBackpackElectropack # Frontier: use NF prefix
  # - HoloprojectorSecurity # Frontier
  - NFPortableRecharger # Frontier: use NF prefix
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - NFTelescopicShield # Frontier: use NF prefix

- type: latheRecipePack
  id: SecurityBoards
  abstract: true # Frontier: finally, spammable shuttle guns
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  #- ExplosivePayload # Frontier
  #- GrenadeBlast # Frontier
  - NFGrenadeEMP # Frontier: use NF prefix
  - NFGrenadeFlash # Frontier: use NF prefix
  - NFMagazineGrenadeEmpty # Frontier: use NF prefix

# Shared between secfab and emagged protolathe
# - type: latheRecipePack # Frontier
  # id: SecurityAmmo # Frontier
  # recipes: # Frontier
  # - BoxBeanbag # Frontier
  # - BoxShotgunIncendiary # Frontier
  # - BoxShotgunUranium # Frontier
  # - BoxShellTranquilizer # Frontier
  # - MagazineBoxLightRifleIncendiary # Frontier
  # - MagazineBoxLightRifleUranium # Frontier
  # - MagazineBoxMagnumIncendiary # Frontier
  # - MagazineBoxMagnumUranium # Frontier
  # - MagazineBoxPistolIncendiary # Frontier
  # - MagazineBoxPistolUranium # Frontier
  # - MagazineBoxRifleIncendiary # Frontier
  # - MagazineBoxRifleUranium # Frontier
  # - MagazineLightRifleIncendiary # Frontier
  # - MagazineLightRifleUranium # Frontier
  # - MagazinePistolIncendiary # Frontier
  # - MagazinePistolUranium # Frontier
  # - MagazinePistolSubMachineGunIncendiary # Frontier
  # - MagazinePistolSubMachineGunUranium # Frontier
  # - MagazineRifleIncendiary # Frontier
  # - MagazineRifleUranium # Frontier
  # - MagazineShotgunBeanbag # Frontier
  # - MagazineShotgunIncendiary # Frontier
  # - SpeedLoaderMagnumIncendiary # Frontier
  # - SpeedLoaderMagnumUranium # Frontier

#- type: latheRecipePack # Frontier
  #id: SecurityWeapons # Frontier
  #recipes: # Frontier
  #- Truncheon # Frontier
  #- WeaponAdvancedLaser # Frontier
  #- WeaponLaserCannon # Frontier
  #- WeaponLaserCarbine # Frontier
  #- WeaponXrayCannon # Frontier
  #- WeaponTemperatureGun # Frontier

#- type: latheRecipePack # Frontier
  #id: SecurityDisablers # Frontier
  #recipes: # Frontier
  #- WeaponDisabler # Frontier
  #- WeaponDisablerSMG # Frontier
