## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - TrashBag
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  # - BiogeneratorMachineCircuitboard # Frontier: dynamic
  - UniformPrinterMachineCircuitboard
  # - MicrowaveMachineCircuitboard # Frontier: dynamic
  # - ReagentGrinderMachineCircuitboard # Frontier: dynamic
  # - ElectricGrillMachineCircuitboard # Frontier: dynamic
  # - BoozeDispenserMachineCircuitboard # Frontier: dynamic
  # - SodaDispenserMachineCircuitboard # Frontier: dynamic

## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  # - BiofabricatorMachineCircuitboard # Frontier
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
