- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # Frontier - 30 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600 # Frontier - 6 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 64800 # 18 hours
  startingGear: BailiffGear
  icon: "JobIconWarden" # Frontier
  supervisors: job-supervisors-sheriff
  canBeAntag: false
  access:
  - Armory
  - Sergeant # Frontier
  - Bailiff # Frontier
  accessGroups: # Frontier
  - GeneralNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Frontier
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BailiffGear
  equipment:
    ears: ClothingHeadsetAltNfsdGreen # Frontier
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorNfsd # Frontier
  storage:
    back:
    - Flash
    - MagazinePistol
    - MagazinePistolRubber
    - BaseSecurityUplinkRadioOfficer
    - NfsdBailiffShipVoucher
