- type: job
  id: DetectiveNF
  name: job-name-detective-nf
  description: job-description-detective-nf
  playTimeTracker: JobDetective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: DetectiveNFGear
  icon: "JobIconNFDetective"
  supervisors: job-supervisors-bailiff
  canBeAntag: false
  access:
  - Detective
  accessGroups: # Frontier
  - GeneralNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: DetectiveNFGear
  equipment:
    ears: ClothingHeadsetNfsdCream
    pocket1: WeaponRevolverInspector
    pocket2: SpeedLoaderMagnum
    neck: ClothingNeckStarSilverBadge # Corvax-Frontier
  storage:
    back:
    - Flash
    - MagazinePistol
    - MagazinePistolRubber
    - ForensicPad
    - ForensicScanner
    - FrontierUplinkCoin10
    - LogProbeCartridge
    - RubberStampDetective
