- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # Frontier - 30 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 32400 # 9 hrs
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer" # Frontier
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNfsdTacBlack # Frontier
    back: ClothingBackpackOfficerFilled # Frontier
    shoes: ClothingShoesBootsNFSDBrown # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    head: ClothingHeadHatNfsdBeretGreen # Frontier
    outerClothing: ClothingOuterCoatNfsdLongCoat # Frontier
    id: NfsdSergeant # Frontier
    ears: ClothingHeadsetAltNFSDbrown # Frontier
    belt: ClothingBeltNfsdFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    gloves: ClothingHandsGlovesCombatNfsdCream # Frontier
    neck: ClothingNeckNfsdBadgeSeniorOfficer # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  satchel: ClothingBackpackSatchelOfficerFilled # Frontier
  duffelbag: ClothingBackpackDuffelOfficerFilled # Frontier
  messenger: ClothingBackpackMessengerOfficerFilled # Frontier
