- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # Frontier - 30 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 43200 # Frontier - 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 32400 # 9 hrs
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer" # Frontier
  supervisors: job-supervisors-bailiff
  canBeAntag: false
  accessGroups: # Frontier
  - GeneralNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    ears: ClothingHeadsetAltNfsdBrown # Frontier
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
