- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # Frontier - 6 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # Frontier - 10 hrs
  startingGear: WardenGear
  icon: "JobIconBailiff" # Frontier
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Frontier

- type: startingGear
  id: WardenGear
  equipment:
    head: ClothingHeadHatNfsdBeretBrown # Frontier
    jumpsuit: ClothingUniformJumpsuitNfsdTacCream # Frontier
    back: ClothingBackpacknfsdFilled # Frontier
    shoes: ClothingShoesBootsNFSDCream # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    outerClothing: ClothingOuterCoatNfsdFormal # Frontier
    id: NfsdBailiff # Frontier
    ears: ClothingHeadsetAltNFSDgreen # Frontierr
    belt: ClothingBeltNfsdWebbingFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorSecurity # Frontier
    gloves: ClothingHandsGlovesCombatNfsdCream # Frontier
    neck: ClothingNeckNfsdBadgeWarden # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  satchel: ClothingBackpackSatchelnfsdFilled # Frontier
  duffelbag: ClothingBackpackDuffelnfsdFilled # Frontier
  messenger: ClothingBackpackMessengerOfficerFilled # Frontier
