- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  startingGear: ValetGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-everyone
  access:
  - Service
  - Bar
  - Kitchen
  - Cargo
  - Maintenance
  - Janitor

- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
    jumpsuit: ClothingUniformJumpsuitBartender
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ValetPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
