- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ValetGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-everyone
  access:
  - Service
  - Bar
  - Kitchen
  - Cargo
  - Maintenance
  - Janitor
  - External # Frontier

- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
    jumpsuit: ClothingUniformJumpsuitValet
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ValetPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtValet
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
